#############################################################################
# Makefile for building: qtRadio
# Generated by qmake (2.01a) (Qt 4.8.6) on: So. Nov 8 21:18:07 2015
# Project:  qtRadio.pro
# Template: app
# Command: /usr/lib/qt4/bin/qmake -o Makefile qtRadio.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I/usr/include/libnm -I/usr/include/mpd -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -L/usr/lib -lmpdclient -lQtDBus -L/usr/lib/qt4 -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		GetIP.cpp \
		MainMenu.cpp \
		MpdWidget.cpp \
		ScrollText.cpp moc_GetIP.cpp \
		moc_MainMenu.cpp \
		moc_MpdWidget.cpp \
		moc_ScrollText.cpp
OBJECTS       = main.o \
		GetIP.o \
		MainMenu.o \
		MpdWidget.o \
		ScrollText.o \
		moc_GetIP.o \
		moc_MainMenu.o \
		moc_MpdWidget.o \
		moc_ScrollText.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtRadio.pro
QMAKE_TARGET  = qtRadio
DESTDIR       = 
TARGET        = qtRadio

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtRadio.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt4/libQtDBus.prl \
		/usr/lib/qt4/libQtXml.prl \
		/usr/lib/qt4/libQtCore.prl \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile qtRadio.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/qt4/libQtDBus.prl:
/usr/lib/qt4/libQtXml.prl:
/usr/lib/qt4/libQtCore.prl:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtRadio.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtRadio1.0.0 || $(MKDIR) .tmp/qtRadio1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtRadio1.0.0/ && $(COPY_FILE) --parents GetIP.h MainMenu.h MpdWidget.h ScrollText.h .tmp/qtRadio1.0.0/ && $(COPY_FILE) --parents main.cpp GetIP.cpp MainMenu.cpp MpdWidget.cpp ScrollText.cpp .tmp/qtRadio1.0.0/ && (cd `dirname .tmp/qtRadio1.0.0` && $(TAR) qtRadio1.0.0.tar qtRadio1.0.0 && $(COMPRESS) qtRadio1.0.0.tar) && $(MOVE) `dirname .tmp/qtRadio1.0.0`/qtRadio1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtRadio1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_GetIP.cpp moc_MainMenu.cpp moc_MpdWidget.cpp moc_ScrollText.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GetIP.cpp moc_MainMenu.cpp moc_MpdWidget.cpp moc_ScrollText.cpp
moc_GetIP.cpp: GetIP.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) GetIP.h -o moc_GetIP.cpp

moc_MainMenu.cpp: GetIP.h \
		MpdWidget.h \
		MainMenu.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) MainMenu.h -o moc_MainMenu.cpp

moc_MpdWidget.cpp: MpdWidget.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) MpdWidget.h -o moc_MpdWidget.cpp

moc_ScrollText.cpp: ScrollText.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) ScrollText.h -o moc_ScrollText.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp MainMenu.h \
		GetIP.h \
		MpdWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

GetIP.o: GetIP.cpp GetIP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GetIP.o GetIP.cpp

MainMenu.o: MainMenu.cpp GetIP.h \
		MainMenu.h \
		MpdWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainMenu.o MainMenu.cpp

MpdWidget.o: MpdWidget.cpp MpdWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MpdWidget.o MpdWidget.cpp

ScrollText.o: ScrollText.cpp ScrollText.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScrollText.o ScrollText.cpp

moc_GetIP.o: moc_GetIP.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GetIP.o moc_GetIP.cpp

moc_MainMenu.o: moc_MainMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainMenu.o moc_MainMenu.cpp

moc_MpdWidget.o: moc_MpdWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MpdWidget.o moc_MpdWidget.cpp

moc_ScrollText.o: moc_ScrollText.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScrollText.o moc_ScrollText.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

